### ISSUE TITLE
no working:(

### ISSUE THREAD

**Issue by exrector** [edx-Achim/ESP8266-HomeKit-Security-System#1]
Arduino ide monitor:
r$$⸮⸮⸮⸮#⸮n⸮$⸮b|⸮⸮⸮⸮r⸮#⸮p⸮⸮oo⸮lNo⸮⸮⸮#p⸮⸮b$ {l⸮{⸮o⸮#⸮o#p⸮
I used for install NodeMCU-PyFlasher-4.0 and 5 mac

**Comment by AchimPieters** [comment]
For more information visit: https://studiopieters.nl

**Comment by exrector** [comment]
@AchimPieters I was already there and I didn't find this project.

**Comment by AchimPieters** [comment]
Did you set the baud rate to 115200?

**Comment by exrector** [comment]
Of course
**QIO variant**
`Command: esptool.py --port /dev/cu.SLAB_USBtoUART --baud 115200 --after no_reset write_flash --flash_size detect --flash_mode qio 0x00000 /Users/exrector/Downloads/main (1).bin --erase-all

esptool.py v3.0
Serial port /dev/cu.SLAB_USBtoUART
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: e8:db:84:a4:4b:a8
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Erasing flash (this may take a while)...
Chip erase completed successfully in 1.0s
Warning: Image file at 0x0 doesn't look like an image file, so not changing any flash settings.
Compressed 433152 bytes to 311435...
Wrote 433152 bytes (311435 compressed) at 0x00000000 in 27.6 seconds (effective 125.7 kbit/s)...
Hash of data verified.

Leaving...
Staying in bootloader.

Firmware successfully flashed. Unplug/replug or reset device 
to switch back to normal boot mode.`

**DIO variant**

`Command: esptool.py --port /dev/cu.SLAB_USBtoUART --baud 115200 --after no_reset write_flash --flash_size detect --flash_mode dio 0x00000 /Users/exrector/Downloads/main (1).bin --erase-all

esptool.py v3.0
Serial port /dev/cu.SLAB_USBtoUART
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: e8:db:84:a4:4b:a8
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Erasing flash (this may take a while)...
Chip erase completed successfully in 0.4s
Warning: Image file at 0x0 doesn't look like an image file, so not changing any flash settings.
Compressed 433152 bytes to 311435...
Wrote 433152 bytes (311435 compressed) at 0x00000000 in 27.6 seconds (effective 125.5 kbit/s)...
Hash of data verified.

Leaving...
Staying in bootloader.

Firmware successfully flashed. Unplug/replug or reset device 
to switch back to normal boot mode.`

**Comment by AchimPieters** [comment]
If you use ESP8266 with 4MB of flash (32m bit), then you're fine. If you have 1MB chip, you need to set following environment variables:
export FLASH_SIZE=8
export HOMEKIT_SPI_FLASH_BASE_ADDR=0x7a000
If you're debugging stuff, or have troubles and want to file issue and attach log, please enable DEBUG output:
export HOMEKIT_DEBUG=1
Depending on your device, it might be required to change the flash mode:
export FLASH_MODE=dout

**Comment by AchimPieters** [comment]
Btw the recommend way is this: https://www.studiopieters.nl/esp-homekit-sdk-revised-installation/

**Comment by exrector** [comment]
If there is an error in your BIN file, then I cannot fix it. Whose repository do you use from github by default for your projects?

**Comment by AchimPieters** [comment]
The bin file is is tested and working. The source code is on this git.

**Comment by exrector** [comment]
@AchimPieters I tried. I really tried to build your project on libraries https://github.com/pfalcon/esp-open-sdk / but I can't. It's so morally outdated. I am not able to do such a downgrade on my mac os.
Can I ask you to deploy the project on a modern library https://github.com/espressif/esp-homekit-sdk 
Unfortunately the compiled BIN is useless and I do not know why

**Comment by exrector** [comment]
MacExrector:scr Exrector$ make all
Toolchain path: /Users/exrector/esp/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc
Toolchain version: esp-2020r3-49-gd5524c1
Compiler version: 8.4.0
Python requirements from /Users/exrector/esp/ESP8266_RTOS_SDK/requirements.txt are satisfied.
GENCONFIG
App "" version: 0.0.1-391-g503e66a
Building partitions from /Users/exrector/esp/ESP8266_RTOS_SDK/components/partition_table/partitions_singleapp.csv...
Python requirements from /Users/exrector/esp/ESP8266_RTOS_SDK/requirements.txt are satisfied.
LD build/bootloader/bootloader.elf
esptool.py v2.4.0
App "" version: 0.0.1-391-g503e66a
CC build/app_update/esp_app_desc.o
AR build/app_update/libapp_update.a
AR build/esp8266/libesp8266.a
Generating esp8266.project.ld
LD build/.elf
/Users/exrector/esp/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/8.4.0/../../../../xtensa-lx106-elf/bin/ld: /Users/exrector/esp-open-rtos/examples/scr/build/esp8266/libesp8266.a(startup.o):(.literal.user_init_entry+0x1c): undefined reference to `app_main'
/Users/exrector/esp/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/8.4.0/../../../../xtensa-lx106-elf/bin/ld: /Users/exrector/esp-open-rtos/examples/scr/build/esp8266/libesp8266.a(startup.o): in function `user_init_entry':
/Users/exrector/esp/ESP8266_RTOS_SDK/components/esp8266/source/startup.c:86: undefined reference to `app_main'
collect2: error: ld returned 1 exit status
make: *** [/Users/exrector/esp-open-rtos/examples/scr/build/.elf] Error 1
MacExrector:scr Exrector$

**Comment by AchimPieters** [comment]
@exrector Why don't you use docker? as described here https://www.studiopieters.nl/esp-homekit-sdk-revised-installation
It doesnt matter that you work on the latest MacOS. I reccomend als the use of LCM, also described in the same blog. Everything working here, so It should als be working with you.

**Comment by exrector** [comment]
@AchimPieters 
MacExrector:esp-homekit-demo Exrector$ docker run -it –rm -v `pwd`:/project -w /project esp-rtos make -C examples/led all
docker: invalid reference format.
See 'docker run --help'.
MacExrector:esp-homekit-demo Exrector$ 


I did everything according to the instructions. I also had to fix it in dockerfiles:
Download base image ubuntu 20.04
FROM ubuntu:20.04 as builder

**>>>>> 21.4**

**Comment by AchimPieters** [comment]
@exrector Did you log in on Docker? Why did you need to change the Docker file from "FROM ubuntu:20.04 as builder >>>>> 21.4" ?

**Comment by exrector** [comment]
@AchimPieters Docker swore and gave an error when compiling dockerfile. I'm still trying to understand the docker principle.
